import type { DataQueryFilters, QuerySummary } from '@fikir/types';
import { exportToExcelHTML, exportToPDF, formatEnum } from '@/lib/export';

export function exportQueryExcel(
  payload: {
    results: Record<string, unknown>[];
    summary: QuerySummary;
    columns: string[];
    filters: DataQueryFilters;
    dataSubject: string;
    generatedBy: string;
    anonymized: boolean;
  },
  t: (key: string, fallback?: string) => string,
) {
  const headers = payload.columns.map((c) => formatEnum(c));
  const rows = payload.results.map((row) =>
    payload.columns.map((col) => String(row[col] ?? '')),
  );

  const summaryRows = [
    [t('export.total', 'Total'), String(payload.summary.total)],
    ...(payload.summary.byGender
      ? [
          [t('export.male', 'Male'), String(payload.summary.byGender.male)],
          [t('export.female', 'Female'), String(payload.summary.byGender.female)],
        ]
      : []),
    ...(payload.summary.byDisabilityType?.map((d) => [d.type, String(d.count)]) ?? []),
    ...(payload.summary.bySubcity?.map((s) => [s.subcity, String(s.count)]) ?? []),
  ];

  const infoRows = [
    [t('export.dataSubject', 'Data Subject'), payload.dataSubject],
    [t('export.generatedBy', 'Generated By'), payload.generatedBy],
    [t('export.generatedAt', 'Generated At'), new Date().toISOString()],
    [t('export.anonymized', 'Anonymized'), payload.anonymized ? t('common.yes', 'Yes') : t('common.no', 'No')],
    [t('export.filters', 'Filters'), JSON.stringify(payload.filters)],
  ];

  const combinedHtml = `
    <h2>${t('export.results', 'Results')}</h2>
    ${tableHtml(headers, rows)}
    <h2>${t('export.summaryStats', 'Summary Statistics')}</h2>
    ${tableHtml([t('export.metric', 'Metric'), t('export.value', 'Value')], summaryRows)}
    <h2>${t('export.queryInfo', 'Query Info')}</h2>
    ${tableHtml([t('export.field', 'Field'), t('export.value', 'Value')], infoRows)}
  `;

  exportToExcelHTML(
    `${t('export.dataQueryExport', 'Data Query Export')}${payload.anonymized ? ` (${t('export.anonymized', 'Anonymized')})` : ''}`,
    headers,
    rows,
    `fikir-query-${Date.now()}.xls`,
  );

  void combinedHtml;
}

export function exportQueryPdf(
  title: string,
  results: Record<string, unknown>[],
  columns: string[],
) {
  const headers = columns.map((c) => formatEnum(c));
  const rows = results
    .map(
      (row) =>
        `<tr>${columns.map((col) => `<td>${String(row[col] ?? '')}</td>`).join('')}</tr>`,
    )
    .join('');

  exportToPDF(
    title,
    `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`,
  );
}

function tableHtml(headers: string[], rows: string[][]) {
  return `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows
    .map((row) => `<tr>${row.map((c) => `<td>${c}</td>`).join('')}</tr>`)
    .join('')}</tbody></table>`;
}
