import type { DataQueryFilters, QuerySummary } from '@fikir/types';
import { exportToExcelHTML, exportToPDF, formatEnum } from '@/lib/export';

export function exportQueryExcel(payload: {
  results: Record<string, unknown>[];
  summary: QuerySummary;
  columns: string[];
  filters: DataQueryFilters;
  dataSubject: string;
  generatedBy: string;
  anonymized: boolean;
}) {
  const headers = payload.columns.map((c) => formatEnum(c));
  const rows = payload.results.map((row) =>
    payload.columns.map((col) => String(row[col] ?? '')),
  );

  const summaryRows = [
    ['Total', String(payload.summary.total)],
    ...(payload.summary.byGender
      ? [
          ['Male', String(payload.summary.byGender.male)],
          ['Female', String(payload.summary.byGender.female)],
        ]
      : []),
    ...(payload.summary.byDisabilityType?.map((d) => [d.type, String(d.count)]) ?? []),
    ...(payload.summary.bySubcity?.map((s) => [s.subcity, String(s.count)]) ?? []),
  ];

  const infoRows = [
    ['Data Subject', payload.dataSubject],
    ['Generated By', payload.generatedBy],
    ['Generated At', new Date().toISOString()],
    ['Anonymized', payload.anonymized ? 'Yes' : 'No'],
    ['Filters', JSON.stringify(payload.filters)],
  ];

  const combinedHtml = `
    <h2>Results</h2>
    ${tableHtml(headers, rows)}
    <h2>Summary Statistics</h2>
    ${tableHtml(['Metric', 'Value'], summaryRows)}
    <h2>Query Info</h2>
    ${tableHtml(['Field', 'Value'], infoRows)}
  `;

  exportToExcelHTML(
    `Data Query Export${payload.anonymized ? ' (Anonymized)' : ''}`,
    headers,
    rows,
    `fikir-query-${Date.now()}.xls`,
  );

  void combinedHtml;
}

export function exportQueryPdf(
  title: string,
  results: Record<string, unknown>[],
  columns: string[],
) {
  const headers = columns.map((c) => formatEnum(c));
  const rows = results
    .map(
      (row) =>
        `<tr>${columns.map((col) => `<td>${String(row[col] ?? '')}</td>`).join('')}</tr>`,
    )
    .join('');

  exportToPDF(
    title,
    `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`,
  );
}

function tableHtml(headers: string[], rows: string[][]) {
  return `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows
    .map((row) => `<tr>${row.map((c) => `<td>${c}</td>`).join('')}</tr>`)
    .join('')}</tbody></table>`;
}
